from app import app, db

class Caixa(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.Date, nullable=False)
    caixa1 = db.Column(db.Integer, nullable=False)
    caixa2 = db.Column(db.Integer, nullable=True)
    caixa3 = db.Column(db.Integer, nullable=True)
    caixa4 = db.Column(db.Integer, nullable=True)
    caixa_total = db.Column(db.Integer, nullable=True)
    dinheiro1 = db.Column(db.Float, nullable=True)
    dinheiro2 = db.Column(db.Float, nullable=True)
    dinheiro3 = db.Column(db.Float, nullable=True)
    dinheiro4 = db.Column(db.Float, nullable=True)
    dinheiro_total = db.Column(db.Float, nullable=True)
    cartao_cred1 = db.Column(db.Float, nullable=True)
    cartao_cred2 = db.Column(db.Float, nullable=True)
    cartao_cred3 = db.Column(db.Float, nullable=True)
    cartao_cred4 = db.Column(db.Float, nullable=True)
    cartao_cred_total = db.Column(db.Float, nullable=True)
    cartao_deb1 = db.Column(db.Float, nullable=True)
    cartao_deb2 = db.Column(db.Float, nullable=True)
    cartao_deb3 = db.Column(db.Float, nullable=True)
    cartao_deb4 = db.Column(db.Float, nullable=True)
    cartao_deb_total = db.Column(db.Float, nullable=True)
    pix1 = db.Column(db.Float, nullable=True)
    pix2 = db.Column(db.Float, nullable=True)
    pix3 = db.Column(db.Float, nullable=True)
    pix4 = db.Column(db.Float, nullable=True)
    pix_total = db.Column(db.Float, nullable=True)
    